version: '3.8'
services:
  pyspark-notebook:
    image: jupyter/pyspark-notebook
    environment:
      - DUCKDB_DB=${DUCKDB_DB}
    volumes:
      - ./workshop:/home/jovyan
    ports:
      - 8888:8888